package com.pos_terminal_simulator.database;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;

public class DatabaseInitializer {

    private final DataSource dataSource;

    public DatabaseInitializer(DataSource dataSource) {
        this.dataSource = dataSource;
    }

    public void initialize() throws Exception {

        System.out.println("========================================");
        System.out.println("Starting database initialization...");
        System.out.println("========================================");

        try (Connection connection = dataSource.getConnection();
             Statement statement = connection.createStatement()) {

            System.out.println(
                    "Database connected: "
                            + connection.getMetaData().getURL()
            );

            // TERMINAL
            System.out.println("Executing TERMINAL table SQL...");

            statement.execute("""
                CREATE TABLE IF NOT EXISTS terminal (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    terminal_id VARCHAR(50) NOT NULL,
                    merchant_id VARCHAR(50),
                    serial_number VARCHAR(100),
                    currency VARCHAR(3),
                    status VARCHAR(20)
                )
            """);

            System.out.println(
                    "SUCCESS: TERMINAL table SQL executed."
            );

            // HEARTBEAT_SETTINGS
            System.out.println(
                    "Executing HEARTBEAT_SETTINGS table SQL..."
            );

            statement.execute("""
                CREATE TABLE IF NOT EXISTS heartbeat_settings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    enabled BOOLEAN NOT NULL,
                    interval_seconds INTEGER NOT NULL
                )
            """);

            System.out.println(
                    "SUCCESS: HEARTBEAT_SETTINGS table SQL executed."
            );

            // CONNECTION_SETTINGS
            System.out.println(
                    "Executing CONNECTION_SETTINGS table SQL..."
            );

            statement.execute("""
                CREATE TABLE IF NOT EXISTS connection_settings (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    pos_management_url VARCHAR(255),
                    switch_host VARCHAR(255),
                    switch_port INTEGER
                )
            """);

            System.out.println(
                    "SUCCESS: CONNECTION_SETTINGS table SQL executed."
            );

            // VERIFY TABLES
            System.out.println("========================================");
            System.out.println("Verifying database tables...");
            System.out.println("========================================");

            try (ResultSet resultSet = statement.executeQuery("""
                    SELECT TABLE_SCHEMA, TABLE_NAME
                    FROM INFORMATION_SCHEMA.TABLES
                    WHERE TABLE_TYPE = 'BASE TABLE'
                      AND TABLE_SCHEMA = 'PUBLIC'
                    ORDER BY TABLE_NAME
                    """)) {

                while (resultSet.next()) {

                    String schema =
                            resultSet.getString("TABLE_SCHEMA");

                    String table =
                            resultSet.getString("TABLE_NAME");

                    System.out.println(
                            "FOUND TABLE: "
                                    + schema
                                    + "."
                                    + table
                    );
                }
            }

            System.out.println("========================================");
            System.out.println("Database initialization completed.");
            System.out.println("========================================");
        }
    }
}
